=== AlenaKretsQA/school/src/main/resources/parsers/xml/course.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:complexType name="onlineCourseType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="url" type="xs:anyURI"/>
            <xs:element name="gradeId" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="onsiteCourseType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="roomNumber" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="attendanceType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="onlineCoursesType">
        <xs:sequence>
            <xs:element name="onlineCourse" type="onlineCourseType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="onsiteCoursesType">
        <xs:sequence>
            <xs:element name="onsiteCourse" type="onsiteCourseType"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="attendancesType">
        <xs:sequence>
            <xs:element name="attendances" type="attendanceType"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="courseType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="courseName" type="xs:string"/>
            <xs:element name="credit" type="xs:decimal"/>
            <xs:element name="onlineCourses" type="onlineCoursesType"/>
            <xs:element name="onsiteCourses" type="onsiteCoursesType"/>
            <xs:element name="attendances" type="attendancesType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Define the main element for course -->
    <xs:element name="course" type="courseType"/>
</xs:schema>

=== AlenaKretsQA/school/target/classes/parsers/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<course xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="course.xsd">
    <id>1</id>
    <courseName>Mathematics</courseName>
    <credit>3.0</credit>

    <onlineCourses>
        <onlineCourse>
            <id>101</id>
            <url>https://example.com/math101</url>
            <!-- TODO Add Grade info -->
        </onlineCourse>
        <onlineCourse>
            <id>102</id>
            <url>https://example.com/math102</url>
            <!-- TODO Add Grade information  -->
        </onlineCourse>
    </onlineCourses>

    <onsiteCourses>
        <onsiteCourse>
            <id>201</id>
            <roomNumber>301</roomNumber>
            <date>2024-01-10T10:00:00</date>
            <!-- TODO Add Attendance information  -->
        </onsiteCourse>
        <onsiteCourse>
            <id>202</id>
            <roomNumber>302</roomNumber>
            <date>2024-01-15T13:30:00</date>
            <!-- TODO Add Attendance information  -->
        </onsiteCourse>
    </onsiteCourses>

    <enrollments>
        <enrollment>
            <id>301</id>
            <enrollmentDate>2024-01-01</enrollmentDate>
        </enrollment>
        <enrollment>
            <id>302</id>
            <enrollmentDate>2024-01-05</enrollmentDate>
        </enrollment>
    </enrollments>
</course>

=== AlenaKretsQA/school/src/main/resources/parsers/xml/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<course xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="course.xsd">
    <id>1</id>
    <courseName>Mathematics</courseName>
    <credit>6.0</credit>

    <onlineCourses>
        <onlineCourse>
            <id>303</id>
            <url>https://example.com/math101</url>
            <gradeId> 11</gradeId>
        </onlineCourse>
        <onlineCourse>
            <id>304</id>
            <url>https://example.com/math102</url>
            <gradeId> 12</gradeId>
        </onlineCourse>
        <onlineCourse>
            <id>305</id>
            <url>https://example.com/math103</url>
            <gradeId> 13</gradeId>
        </onlineCourse>
        <onlineCourse>
            <id>306</id>
            <url>https://example.com/math104</url>
            <gradeId> 14</gradeId>
        </onlineCourse>
        <onlineCourse>
            <id>307</id>
            <url>https://example.com/math105</url>
            <gradeId> 15</gradeId>
        </onlineCourse>
    </onlineCourses>
    <onsiteCourses>
        <onsiteCourse>
            <id>402</id>
            <roomNumber>103</roomNumber>
            <date>2023-01-01</date>
        </onsiteCourse>
    </onsiteCourses>
    <attendance>
        <attendances>
            <id>2002</id>
            <status>"Present"</status>
            <date>2023-01-01</date>
        </attendances>
    </attendance>


</course>
